#!/usr/bin/env bash

# setup vim to use fd as fzf backend
export FZF_DEFAULT_COMMAND='fd --type f --follow'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# setup nvim
export VIMCONFIG=~/.config/nvim
export VIMDATA=~/.local/share/nvim
export VISUAL=nvim
alias vim=nvim
