# oh-my-zsh settings
export ZSH="$HOME/.oh-my-zsh"
export ZSH_CUSTOM="$ZSH/custom"
ZSH_THEME="powerlevel10k/powerlevel10k"
export UPDATE_ZSH_DAYS=150
export ZSH_DISABLE_COMPFIX="true"
plugins=(git zsh-completions zsh-autosuggestions zsh-syntax-highlighting)
# reload completion
# autoload -U compinit && compinit
source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# setup vim to use fd as fzf backend
export FZF_DEFAULT_COMMAND='fd --type f --follow'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

# setup nvim
export VIMCONFIG=~/.config/nvim
export VIMDATA=~/.local/share/nvim
export VISUAL=nvim
alias vim=nvim

# make sure these lines are at the end of this file
# local or work configurations not stored in this repo
[[ ! -f ~/.zshrc-work ]] || source ~/.zshrc-work
[[ ! -f ~/.zshrc-local ]] || source ~/.zshrc-local
